[package]
name = "cubeb-core"
version = "0.4.0"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>"]
license = "ISC"
keywords = ["cubeb"]
repository = "https://github.com/djg/cubeb-rs"
homepage = "https://github.com/djg/cubeb-rs"
description = """
Common types and definitions for cubeb rust and C bindings. Not intended for direct use.
"""
categories = ["api-bindings"]

[dependencies]
bitflags = "0.9"
cubeb-sys = { path = "../cubeb-sys" }
