[package]
name = "cubeb-pulse"
version = "0.0.1"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>"]
description = "Cubeb backed for Pulse Audio written in Rust"

[lib]
crate-type = ["staticlib"]

[dependencies]
cubeb-ffi = { path = "cubeb-ffi" }
libc = "*"
libpulse-sys = { path = "libpulse-sys" }
