[package]
name = "systest"
version = "0.1.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
build = "build.rs"

[dependencies]
cubeb-sys = { path = ".." }

[build-dependencies]
ctest = "0.1"